spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poem
    username: root
    password: zsh123
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://localhost:27017/poem
    redis:
      host: localhost
      port: 6379
      database: 0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: ns-like

server:
  port: 8083

eureka:
  client:
    service-url:
     defaultZone: http://localhost:8080/eureka/

logging:
  level:
    root: INFO
    org.springframework.data.mongodb: DEBUG
    org.hibernate.SQL: DEBUG
    com.netflix.discovery: DEBUG
