server:
  port: 8081

spring:
  application:
    name: ns-like # 服务的名称，Eureka 中注册的服务名
  datasource:
    # 如果有数据库配置，保留数据源相关配置
    url: jdbc:mysql://localhost:3306/poem
    username: root
    password: zsh123
  data:
    mongodb:
      uri: mongodb://localhost:27017/poem # MongoDB 配置

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.sspu.nslike: DEBUG
    org.springframework.web: DEBUG