spring:
  application:
    name: ns-comment
  data:
    mongodb:
      uri: mongodb://localhost:27017/poem
  datasource:
    url: jdbc:mysql://localhost:3306/poem
    username: root
    password: cdj123

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
