# @file application.yml
# @description Eureka 服务器配置文件
# 功能：
# 1. 配置服务器端口
# 2. 配置 Eureka 服务器属性
# 3. 配置服务注册行为
# 4. 配置应用名称
# 5. 配置服务同步时间

server:
  port: 8080  # Eureka 服务默认运行端口

eureka:
  client:
    register-with-eureka: false  # 服务端自身不需要注册到Eureka
    fetch-registry: false       # 不从其他服务端获取注册信息
  server:
    wait-time-in-ms-when-sync-empty: 0

spring:
  application:
    name: eureka-server

#spring:
#  application:
#    name: demo-service
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
