spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poem?useSSL=false&serverTimezone=UTC
    username: root
    password: cdj123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: ns-user
  security:
      basic:
        enabled: false


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
