spring:
  application:
    name: ns-recommend
  data:
    mongodb:
      uri: mongodb://localhost:27017/poem
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/poem
    username: root
    password: cdj123
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
