server:
  port: 8082 # 启动服务的端口号，可以根据需求修改

spring:
  application:
    name: ns-rank # 应用名称
  data:
    mongodb:
      uri: mongodb://localhost:27017/poem # MongoDB连接配置
    redis:
      database: 0
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/poem?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: cdj123
    driver-class-name: com.mysql.cj.jdbc.Driver
