server:
  port: 8083

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ns-rank
  # Redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  # MySQL配置
  datasource:
    url: jdbc:mysql://localhost:3306/poem?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: zsh123
    driver-class-name: com.mysql.cj.jdbc.Driver
  # MongoDB配置
  data:
    mongodb:
      uri: mongodb://localhost:27017/poem

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
