server:
  port: 8086 # 服务运行端口，可根据需要修改

spring:
  application:
    name: ns-rank # 应用名称，用于 Eureka 注册
  datasource:
    url: jdbc:mysql://localhost:3306/poem?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: cdj123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 自动更新表结构，可根据需要改为 none 或 validate
    show-sql: true # 显示SQL语句
    database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    mongodb:
      host: localhost
      port: 27017
      database: poem # MongoDB 数据库名称
    redis:
      host: localhost
      port: 6379
      database: 0
  web:
    resources:
          add-mappings: false # 禁用静态资源路径映射

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/ # Eureka 服务地址
    register-with-eureka: true # 是否将此服务注册到 Eureka
    fetch-registry: true # 是否从 Eureka 获取服务注册表



