server:
  port: 8086 # 指定 ns-rank 模块的端口号

spring:
  application:
    name: ns-rank # 服务名称，注册到 Eureka 中的名称
  datasource:
    url: jdbc:mysql://localhost:3306/poem?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: cdj123
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: localhost
      port: 27017
      database: poem # MongoDB 数据库名称
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/ # Eureka 服务注册中心地址
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: info
    org.springframework: debug # 设置Spring日志级别为debug

management:
  endpoints:
    web:
      exposure:
        include: "*" # 开启所有 actuator 端点
  endpoint:
    health:
      show-details: always # 在 /actuator/health 中显示详细信息
