server:
  port: 8081 # 网关服务端口号

spring:
  application:
    name: ns-gateway # 网关服务名
  cloud:
    gateway:
      routes:
        # 路由到 ns-rank 服务
        - id: ns-rank
          uri: lb://ns-rank
          predicates:
            - Path=/api/rank/**

        # 路由到 ns-like 服务
        - id: ns-like
          uri: lb://ns-like
          predicates:
            - Path=/api/likes/**

        # 路由到 ns-user 服务
        - id: ns-user
          uri: lb://ns-user
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        # 路由到 ns-comment 服务
        - id: ns-comment
          uri: lb://ns-comment
          predicates:
            - Path=/api/comments/**

        # 路由到 ns-recommend 服务
        - id: ns-recommend
          uri: lb://ns-recommend
          predicates:
            - Path=/api/recommend/**

        - id: ns-search
          uri: lb://ns-search
          predicates:
            - Path=/api/search/**

    discovery:
      locator:
        enabled: true # 开启服务发现

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/ # Eureka 服务注册地址
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
